using System.Diagnostics;
using System.Drawing.Drawing2D;
using System.Net.NetworkInformation;
using System.Text;
using System.Text.RegularExpressions;

namespace CrossFireRouteLab;

public sealed class MainForm : Form
{
    static readonly Color Bg=Color.FromArgb(5,8,17), Panel=Color.FromArgb(9,15,29), Panel2=Color.FromArgb(12,20,38), Border=Color.FromArgb(35,57,88), Cyan=Color.FromArgb(0,220,255), Purple=Color.FromArgb(177,77,255), Green=Color.FromArgb(40,235,110), Txt=Color.FromArgb(225,235,248), Muted=Color.FromArgb(135,155,180);
    readonly TextBox target=new(); readonly RichTextBox log=new(); readonly Label status=new(), network=new(), active=new(), best=new(); readonly FlowLayoutPanel memoryPanel=new(); readonly List<Button> buttons=new(); readonly List<GameProfile> memory=new(); Icon? appIcon; bool busy;

    public MainForm(){ Text="Game Route Lab"; Width=1500; Height=940; MinimumSize=new Size(1200,760); StartPosition=FormStartPosition.CenterScreen; BackColor=Bg; ForeColor=Txt; Font=new Font("Segoe UI",9.5f); appIcon=Brand.CreateIcon(); Icon=appIcon; BuildUi(); memory.AddRange(GameProfileStore.Load()); RefreshMemory(); L("GAME ROUTE LAB v4.0"); L("Smart game detection • ISP • router • endpoint • route analysis • local game memory"); L("READ-ONLY: no routes, DNS, PPPoE, router settings or firmware are changed."); }

    void BuildUi(){
        var root=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=3,ColumnCount=1,BackColor=Bg}; root.RowStyles.Add(new RowStyle(SizeType.Absolute,116)); root.RowStyles.Add(new RowStyle(SizeType.Absolute,72)); root.RowStyles.Add(new RowStyle(SizeType.Percent,100)); Controls.Add(root);
        var h=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(3,6,14),Padding=new Padding(18)}; h.Paint+=PaintHeader; h.Controls.Add(new PictureBox{Size=new Size(88,88),Location=new Point(18,12),Image=Brand.CreateLogo(84),BackColor=Color.Transparent}); h.Controls.Add(new Label{Text="GAME ROUTE LAB",AutoSize=true,Location=new Point(118,18),Font=new Font("Segoe UI Semibold",26,FontStyle.Bold),ForeColor=Color.White}); h.Controls.Add(new Label{Text="SMARTER ROUTES.  BETTER PING.",AutoSize=true,Location=new Point(120,62),ForeColor=Cyan,Font=new Font("Segoe UI Semibold",10.5f)}); network.Text="NETWORK: NOT SCANNED"; network.AutoSize=true; network.Anchor=AnchorStyles.Top|AnchorStyles.Right; network.Location=new Point(1060,26); network.ForeColor=Muted; status.Text="● READY • READ-ONLY"; status.AutoSize=true; status.Anchor=AnchorStyles.Top|AnchorStyles.Right; status.Location=new Point(1060,60); status.ForeColor=Green; h.Controls.Add(network); h.Controls.Add(status); root.Controls.Add(h,0,0);
        var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,10,12,10),BackColor=Color.FromArgb(7,12,24),WrapContents=false,AutoScroll=true}; target.Width=190; target.BackColor=Panel2; target.ForeColor=Txt; target.BorderStyle=BorderStyle.FixedSingle; target.PlaceholderText="Optional IP / hostname"; bar.Controls.Add(new Label{Text="ENDPOINT",AutoSize=true,ForeColor=Muted,Padding=new Padding(3,9,3,0)}); bar.Controls.Add(target); AddButton(bar,"◎  AUTO ANALYZE",AutoAnalyze); AddButton(bar,"↻  REFRESH GAMES",DetectGames); AddButton(bar,"⌁  NETWORK",DetectNetwork); AddButton(bar,"▣  ROUTER",DetectRouter); AddButton(bar,"⌕  CONNECTIONS",Connections); AddButton(bar,"⌁  ROUTE TABLE",Routes); AddButton(bar,"◉  PING 30x",Ping); AddButton(bar,"⇢  TRACEROUTE",Trace); AddButton(bar,"▥  PATH QUALITY",Path); AddButton(bar,"▤  SAVE REPORT",SaveReport); root.Controls.Add(bar,0,1);
        var body=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,8,12,12),BackColor=Bg,ColumnCount=3}; body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,250)); body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100)); body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,300)); root.Controls.Add(body,0,2);
        var left=Card(); left.Controls.Add(new Label{Text="GAME MEMORY",Dock=DockStyle.Top,Height=38,Padding=new Padding(14,11,0,0),ForeColor=Purple,Font=new Font("Segoe UI Semibold",11,FontStyle.Bold)}); memoryPanel.Dock=DockStyle.Fill; memoryPanel.FlowDirection=FlowDirection.TopDown; memoryPanel.WrapContents=false; memoryPanel.AutoScroll=true; memoryPanel.Padding=new Padding(8); left.Controls.Add(memoryPanel); body.Controls.Add(left,0,0);
        var center=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,RowCount=3}; center.RowStyles.Add(new RowStyle(SizeType.Absolute,155)); center.RowStyles.Add(new RowStyle(SizeType.Absolute,170)); center.RowStyles.Add(new RowStyle(SizeType.Percent,100)); body.Controls.Add(center,1,0);
        var hero=Card(); hero.Controls.Add(new Label{Text="AUTO ANALYSIS",Location=new Point(18,15),AutoSize=true,ForeColor=Purple,Font=new Font("Segoe UI Semibold",16,FontStyle.Bold)}); active.Text="No game selected"; active.Location=new Point(20,52); active.AutoSize=true; active.Font=new Font("Segoe UI Semibold",13); hero.Controls.Add(active); hero.Controls.Add(new Label{Text="Detects the game, finds public connections, fingerprints the network and ranks route evidence automatically.",Location=new Point(20,82),AutoSize=false,Width=720,Height=40,ForeColor=Muted}); center.Controls.Add(hero,0,0);
        var result=Card(); result.Controls.Add(new Label{Text="CURRENT RESULT",Location=new Point(18,12),AutoSize=true,ForeColor=Cyan,Font=new Font("Segoe UI Semibold",11,FontStyle.Bold)}); best.Text="Waiting for analysis…"; best.Location=new Point(20,45); best.AutoSize=false; best.Width=780; best.Height=110; best.Font=new Font("Segoe UI Semibold",14); result.Controls.Add(best); center.Controls.Add(result,0,1);
        var console=Card(); console.Controls.Add(new Label{Text="LIVE ANALYSIS CONSOLE",Location=new Point(18,12),AutoSize=true,ForeColor=Cyan,Font=new Font("Segoe UI Semibold",11,FontStyle.Bold)}); log.Dock=DockStyle.Fill; log.Margin=new Padding(14,42,14,12); log.BackColor=Color.FromArgb(3,7,14); log.ForeColor=Txt; log.BorderStyle=BorderStyle.None; log.Font=new Font("Cascadia Mono",9.5f); log.WordWrap=false; log.ReadOnly=true; console.Controls.Add(log); center.Controls.Add(console,0,2);
        var right=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,RowCount=3}; right.RowStyles.Add(new RowStyle(SizeType.Absolute,205)); right.RowStyles.Add(new RowStyle(SizeType.Absolute,205)); right.RowStyles.Add(new RowStyle(SizeType.Percent,100)); right.Controls.Add(InfoCard("NETWORK INFORMATION","ISP / organization / ASN / public IP / gateway / DNS",Cyan),0,0); right.Controls.Add(InfoCard("ROUTER INTELLIGENCE","Vendor / model / firmware / management interface",Purple),0,1); right.Controls.Add(InfoCard("ANALYZER TIPS","Run inside an online match. More observations improve each game's local memory.",Green),0,2); body.Controls.Add(right,2,0);
    }
    Panel Card(){var p=new Panel{Dock=DockStyle.Fill,BackColor=Panel,Margin=new Padding(0,0,0,8),Padding=new Padding(12)}; p.Paint+=PaintCard; return p;}
    Panel InfoCard(string title,string text,Color accent){var p=Card(); p.Controls.Add(new Label{Text=title,Location=new Point(14,12),AutoSize=true,ForeColor=accent,Font=new Font("Segoe UI Semibold",11,FontStyle.Bold)}); p.Controls.Add(new Label{Text=text,Location=new Point(14,47),AutoSize=false,Width=260,Height=120,ForeColor=Muted}); return p;}
    void AddButton(Control c,string text,Func<Task> action){var b=new Button{Text=text,AutoSize=true,Height=40,FlatStyle=FlatStyle.Flat,BackColor=Panel2,ForeColor=Txt,Margin=new Padding(4)}; b.FlatAppearance.BorderColor=Border; b.FlatAppearance.MouseOverBackColor=Color.FromArgb(24,35,60); b.Click+=async(_,_)=>await Safe(action); buttons.Add(b); c.Controls.Add(b);}
    void PaintHeader(object? s,PaintEventArgs e){using var b=new LinearGradientBrush(new Rectangle(0,0,e.ClipRectangle.Width,6),Purple,Cyan,LinearGradientMode.Horizontal); e.Graphics.FillRectangle(b,0,e.ClipRectangle.Bottom-5,e.ClipRectangle.Width,5);}
    void PaintCard(object? s,PaintEventArgs e){var r=((Control)s!).ClientRectangle;r.Width--;r.Height--;using var p=new Pen(Border);e.Graphics.DrawRectangle(p,r);}
    void L(string s){if(InvokeRequired){BeginInvoke(()=>L(s));return;}log.AppendText(s+Environment.NewLine);log.SelectionStart=log.TextLength;log.ScrollToCaret();}
    async Task Safe(Func<Task> f){if(busy)return;busy=true;foreach(var b in buttons)b.Enabled=false;status.Text="● ANALYZING…";status.ForeColor=Color.Gold;try{await f();}catch(Exception e){L("[ERROR] "+e.Message);status.Text="● ERROR • SEE CONSOLE";status.ForeColor=Color.OrangeRed;}finally{busy=false;foreach(var b in buttons)b.Enabled=true;if(!status.Text.StartsWith("● ERROR")){status.Text="● READY • READ-ONLY";status.ForeColor=Green;}}}

    void RefreshMemory(){memoryPanel.SuspendLayout();memoryPanel.Controls.Clear();foreach(var p in memory.OrderByDescending(x=>x.LastSeenUtc)){var c=new Panel{Width=220,Height=76,BackColor=Panel2,Margin=new Padding(0,0,0,8),Cursor=Cursors.Hand};c.Paint+=(_,e)=>{using var pen=new Pen(p.LastScore>=70?Green:Border);e.Graphics.DrawRectangle(pen,0,0,c.Width-1,c.Height-1);};var img=new PictureBox{Size=new Size(54,54),Location=new Point(10,10),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.FromArgb(2,5,11)};try{img.Image=File.Exists(p.IconPath)?Image.FromFile(p.IconPath):Brand.CreateLogo(50);}catch{img.Image=Brand.CreateLogo(50);}var n=new Label{Text=p.DisplayName,Location=new Point(72,9),AutoSize=false,Width=135,Height=23,ForeColor=Txt,Font=new Font("Segoe UI Semibold",10,FontStyle.Bold)};var i=new Label{Text=p.Observations+" analyses\n"+(string.IsNullOrWhiteSpace(p.LastBestEndpoint)?"No result yet":"Best: "+p.LastBestEndpoint),Location=new Point(72,32),AutoSize=false,Width=135,Height=38,ForeColor=p.LastScore>=70?Green:Muted};c.Controls.Add(img);c.Controls.Add(n);c.Controls.Add(i);c.Click+=(_,_)=>SelectProfile(p);img.Click+=(_,_)=>SelectProfile(p);n.Click+=(_,_)=>SelectProfile(p);i.Click+=(_,_)=>SelectProfile(p);memoryPanel.Controls.Add(c);}if(memory.Count==0)memoryPanel.Controls.Add(new Label{Text="No games remembered yet.\n\nStart a game and click\nAUTO ANALYZE.",ForeColor=Muted,AutoSize=true,Padding=new Padding(8)});memoryPanel.ResumeLayout();}
    void SelectProfile(GameProfile p){active.Text=$"{p.DisplayName}  •  {p.Observations} saved analyses";best.Text=string.IsNullOrWhiteSpace(p.LastBestEndpoint)?"No route result stored yet.":$"LAST BEST\n{p.LastBestEndpoint}   |   score {p.LastScore:0}/100\nLast scan: {p.LastSeenUtc.ToLocalTime():g}";L($"\n[MEMORY] {p.DisplayName}\nExecutable: {p.ExecutablePath}\nObservations: {p.Observations}\nLast best: {p.LastBestEndpoint}");}
    void Upsert(GameProfile p){var n=memory.FindIndex(x=>x.Key==p.Key);if(n>=0)memory[n]=p;else memory.Add(p);}

    async Task DetectGames(){L("\n=== ANY-GAME DISCOVERY ===");var items=await GameScanner.DiscoverAsync();var groups=items.Where(x=>x.LikelyGame).GroupBy(x=>new{x.Pid,x.ProcessName,x.ExecutablePath}).ToList();if(groups.Count==0){L("No high-confidence game process found. Start an online game and try again.");return;}foreach(var g in groups){var p=GameProfileStore.Touch(g.Key.ProcessName,g.Key.ExecutablePath);Upsert(p);L($"GAME {p.DisplayName} PID={g.Key.Pid} endpoints={g.Count()} confidence={g.Max(x=>x.Confidence)}%");}RefreshMemory();}
    async Task AutoAnalyze(){L("\n============================================================\nAUTO ANALYSIS STARTED\n============================================================");var r=await RouterDetector.DetectAsync();var n=await NetworkProfileDetector.DetectAsync();network.Text=$"ISP: {n.ISP} | ASN: {n.ASN} | ROUTER: {r.Model}";L($"NETWORK: {n.ISP} | {n.Organization} | ASN {n.ASN} | Public {n.PublicIp} | GW {n.Gateway}");L($"ROUTER: {r.Vendor} {r.Model} | FW {r.Firmware} | confidence {r.Confidence}");var all=await GameScanner.DiscoverAsync();var game=all.Where(x=>x.LikelyGame).OrderByDescending(x=>x.Confidence).FirstOrDefault();if(game==null){active.Text="No game detected";best.Text="Start an online game first, then run AUTO ANALYZE again.";L("STOP: no high-confidence game was detected. The analyzer will not guess ChatGPT, Chrome, Discord or another normal application as a game.");return;}var p=GameProfileStore.Touch(game.ProcessName,game.ExecutablePath);Upsert(p);RefreshMemory();active.Text=$"{p.DisplayName} • PID {game.Pid} • confidence {game.Confidence}%";L($"GAME: {p.DisplayName} | PID {game.Pid} | {p.ExecutablePath}");var candidates=all.Where(x=>x.Pid==game.Pid&&x.LikelyGame).GroupBy(x=>$"{x.RemoteIp}:{x.RemotePort}/{x.Protocol}").Select(g=>g.First()).Take(10).ToList();if(candidates.Count==0){L("Game process detected, but no public game sockets are visible. Enter an online match and retry.");return;}L($"FOUND {candidates.Count} candidate game endpoint(s). Testing automatically — no IP copying required.");var results=new List<(GameEndpoint E,double Score,string Evidence)>();foreach(var e in candidates){var probe=await PingProbe(e.RemoteIp);var tr=await Cmd("tracert.exe",$"-d -h 18 -w 500 {e.RemoteIp}",25000);var(hops,last)=ParseTrace(tr);var score=Score(e,probe,hops,last);var ev=$"ICMP {probe.Text}; hops {hops}; last RTT {last:0.0} ms";results.Add((e,score,ev));L($"{e.RemoteIp}:{e.RemotePort} {e.Protocol} -> score {score:0}/100 | {ev}");}var bestResult=results.OrderByDescending(x=>x.Score).First();GameProfileStore.Record(p,$"{bestResult.E.RemoteIp}:{bestResult.E.RemotePort}",bestResult.Score,bestResult.Evidence);p=GameProfileStore.Load().FirstOrDefault(x=>x.Key==p.Key)??p;Upsert(p);RefreshMemory();best.Text=$"BEST CURRENT ENDPOINT\n{bestResult.E.RemoteIp}:{bestResult.E.RemotePort}  {bestResult.E.Protocol}\nScore {bestResult.Score:0}/100 • {bestResult.Evidence}";L($"BEST: {bestResult.E.RemoteIp}:{bestResult.E.RemotePort} ({bestResult.E.Protocol}) | score {bestResult.Score:0}/100");L("ICMP timeout is treated as unknown/blocked, not automatic game packet loss. No routing settings were changed.");}
    async Task<Probe> PingProbe(string ip){using var p=new Ping();var v=new List<long>();for(int i=0;i<5;i++){try{var x=await p.SendPingAsync(ip,800);if(x.Status==IPStatus.Success)v.Add(x.RoundtripTime);}catch{}}return v.Count==0?new Probe(0,"blocked / no response"):new Probe(v.Average(),$"{v.Average():0}ms avg, {5-v.Count}/5 lost");}
    readonly record struct Probe(double Avg,string Text);
    static double Score(GameEndpoint e,Probe p,int hops,double last){double s=e.Confidence*.35;if(p.Avg>0)s+=Math.Max(0,40-Math.Min(40,p.Avg*.45));else s+=18;if(last>0)s+=Math.Max(0,18-Math.Min(18,last*.2));if(hops>0)s+=Math.Max(0,7-Math.Min(7,hops*.18));return Math.Clamp(s,0,100);}
    static(int Hops,double Last)ParseTrace(string t){int h=0;double last=0;foreach(var line in t.Split('\n')){var m=Regex.Match(line.Trim(),@"^(\d+)\s+(.*)$");if(!m.Success)continue;var ts=Regex.Matches(m.Groups[2].Value,@"<?(\d+)\s*ms").Cast<Match>().Select(x=>double.Parse(x.Groups[1].Value)).ToList();if(ts.Count>0){h++;last=ts.Average();}}return(h,last);}

    async Task DetectNetwork(){var n=await NetworkProfileDetector.DetectAsync();network.Text=$"ISP: {n.ISP} | ASN: {n.ASN} | GW: {n.Gateway}";L($"\n=== NETWORK / ISP ===\nInterface: {n.InterfaceName}\nLocal IP: {n.LocalIp}\nGateway: {n.Gateway}\nWAN: {n.WanType}\nPublic IP: {n.PublicIp}\nISP: {n.ISP}\nOrganization: {n.Organization}\nASN: {n.ASN}\nLocation: {n.City}, {n.Country}\nDNS: {n.DnsServers}");}
    async Task DetectRouter(){var r=await RouterDetector.DetectAsync();L($"\n=== ROUTER FINGERPRINT ===\nGateway: {r.Gateway}\nVendor: {r.Vendor}\nModel: {r.Model}\nFirmware: {r.Firmware}\nManagement UI: {r.ManagementUrl}\nConfidence: {r.Confidence}\nNotes: {r.Notes}");}
    async Task Connections(){L("\n=== CONNECTIONS ===");L(await Cmd("netstat.exe","-ano",20000));}
    async Task Routes(){L("\n=== ROUTE TABLE ===");L(await Cmd("route.exe","print",20000));}
    async Task Ping(){var ip=target.Text.Trim();if(ip==""){L("Enter an endpoint or run AUTO ANALYZE first.");return;}L($"\n=== PING 30x {ip} ===");L(await Cmd("ping.exe",$"-n 30 {ip}",50000));}
    async Task Trace(){var ip=target.Text.Trim();if(ip==""){L("Enter an endpoint or run AUTO ANALYZE first.");return;}L($"\n=== TRACEROUTE {ip} ===");L(await Cmd("tracert.exe",$"-d -h 30 {ip}",60000));}
    async Task Path(){var ip=target.Text.Trim();if(ip==""){L("Enter an endpoint or run AUTO ANALYZE first.");return;}L($"\n=== PATH QUALITY {ip} ===");L(await Cmd("pathping.exe",$"-n -q 10 -p 250 {ip}",180000));}
    async Task<string> Cmd(string file,string args,int timeout){using var p=Process.Start(new ProcessStartInfo(file,args){RedirectStandardOutput=true,RedirectStandardError=true,UseShellExecute=false,CreateNoWindow=true,StandardOutputEncoding=Encoding.UTF8})??throw new Exception("Could not start "+file);var o=p.StandardOutput.ReadToEndAsync();var er=p.StandardError.ReadToEndAsync();using var c=new CancellationTokenSource(timeout);try{await p.WaitForExitAsync(c.Token);}catch{try{p.Kill(true);}catch{}return(await o)+"\nTIMEOUT\n"+await er;}return await o+"\n"+await er;}
    async Task SaveReport(){using var s=new SaveFileDialog{Filter="Text report|*.txt",FileName=$"GameRouteLab_{DateTime.Now:yyyyMMdd_HHmmss}.txt"};if(s.ShowDialog(this)!=DialogResult.OK)return;await File.WriteAllTextAsync(s.FileName,log.Text);L("Report saved: "+s.FileName);}
    protected override void Dispose(bool disposing){if(disposing)appIcon?.Dispose();base.Dispose(disposing);}
}
