using System.Diagnostics;
using System.Drawing.Drawing2D;
using System.Net;
using System.Net.NetworkInformation;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Runtime.InteropServices;

namespace CrossFireRouteLab;

public sealed class ModernMainForm : Form
{
    static readonly Color Bg=Color.FromArgb(2,5,13), Card=Color.FromArgb(6,12,25), Card2=Color.FromArgb(9,17,34), Line=Color.FromArgb(27,54,88), Cyan=Color.FromArgb(0,224,255), Purple=Color.FromArgb(181,70,255), Green=Color.FromArgb(34,240,106), Yellow=Color.FromArgb(255,207,56), Text=Color.FromArgb(235,244,255), Muted=Color.FromArgb(135,159,190), Red=Color.FromArgb(255,74,115);
    readonly FlowLayoutPanel memoryList=new(); readonly RichTextBox console=new(); readonly Label gameName=new(), gameMeta=new(), networkInfo=new(), routerInfo=new(), bestEndpoint=new(), bestMetrics=new(), qualityState=new(), tipText=new(), footer=new(), progressText=new(); readonly Panel graph=new(); readonly ProgressBar progress=new(); readonly TextBox endpoint=new(); readonly List<GameRecord> memory=new(); readonly List<IconButton> actions=new(); bool busy;
    GameRecord? current; readonly string dataDir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"GameRouteLab");

    public ModernMainForm(){Text="Game Route Lab";Width=1600;Height=980;MinimumSize=new Size(1250,780);StartPosition=FormStartPosition.CenterScreen;BackColor=Bg;ForeColor=Text;Font=new Font("Segoe UI",9.5f);DoubleBuffered=true;try{Icon=BrandIcon();}catch{}Directory.CreateDirectory(dataDir);LoadMemory();Build();RefreshMemory();Write("GAME ROUTE LAB v5.0");Write("Smart game detection • ISP • router • endpoint • route quality • local game memory");Write("READ-ONLY MODE: the application does not change routes, DNS, PPPoE, router settings or firmware.");}

    void Build(){
        var root=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,ColumnCount=1,RowCount=3,Padding=new Padding(0)};root.RowStyles.Add(new RowStyle(SizeType.Absolute,150));root.RowStyles.Add(new RowStyle(SizeType.Absolute,112));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));Controls.Add(root);
        root.Controls.Add(BuildHeader(),0,0);root.Controls.Add(BuildToolbar(),0,1);
        var body=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,ColumnCount=3,Padding=new Padding(12,4,12,10)};body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,285));body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,355));root.Controls.Add(body,0,2);
        body.Controls.Add(BuildLeft(),0,0);body.Controls.Add(BuildCenter(),1,0);body.Controls.Add(BuildRight(),2,0);
    }

    Control BuildHeader(){var p=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(1,3,9)};p.Paint+=HeaderPaint;var logo=new PictureBox{Image=MakeLogo(116),Size=new Size(120,120),Location=new Point(28,12),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.Transparent};p.Controls.Add(logo);p.Controls.Add(Label("GAME ROUTE LAB",new Point(160,27),new Size(420,42),new Font("Segoe UI Semibold",31,FontStyle.Bold),Text));p.Controls.Add(Label("SMARTER ROUTES.  BETTER PING.",new Point(164,75),new Size(400,26),new Font("Segoe UI Semibold",12,FontStyle.Bold),Cyan));p.Controls.Add(Label("LOCAL-FIRST GAME NETWORK ANALYZER",new Point(165,103),new Size(420,22),new Font("Segoe UI",9,FontStyle.Regular),Muted));return p;}

    Control BuildToolbar(){var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(3,7,16),Padding=new Padding(12,8,12,8),WrapContents=false,AutoScroll=true};endpoint.Width=185;endpoint.Height=42;endpoint.BackColor=Card2;endpoint.ForeColor=Text;endpoint.BorderStyle=BorderStyle.FixedSingle;endpoint.Font=new Font("Segoe UI",10);endpoint.PlaceholderText="Optional IP / hostname";bar.Controls.Add(Label("ENDPOINT",Point.Empty,new Size(68,42),new Font("Segoe UI",8,FontStyle.Bold),Muted));bar.Controls.Add(endpoint);
        AddAction(bar,"◎","AUTO ANALYZE",AutoAnalyze,Purple);AddAction(bar,"⌁","REFRESH GAMES",RefreshGames,Cyan);AddAction(bar,"◌","DETECT NETWORK",DetectNetwork,Cyan);AddAction(bar,"▣","DETECT ROUTER",DetectRouter,Purple);AddAction(bar,"⌕","FIND CONNECTIONS",FindConnections,Cyan);AddAction(bar,"⌁","ROUTE TABLE",RouteTable,Cyan);AddAction(bar,"◉","PING 30x",Ping30,Green);AddAction(bar,"⇢","TRACEROUTE",Traceroute,Purple);AddAction(bar,"▥","PATH QUALITY",PathQuality,Green);AddAction(bar,"▤","SAVE REPORT",SaveReport,Purple);return bar;}

    void AddAction(Control parent,string glyph,string title,Func<Task> action,Color accent){var b=new IconButton(glyph,title,accent){Width=112,Height=78,Margin=new Padding(4,2,4,2)};b.Click+=async(_,_)=>await Safe(action);actions.Add(b);parent.Controls.Add(b);}

    Control BuildLeft(){var outer=CardPanel();outer.Controls.Add(Label("GAME MEMORY",new Point(18,15),new Size(220,28),new Font("Segoe UI Semibold",13,FontStyle.Bold),Purple));var line=Label("YOUR LOCAL HISTORY",new Point(18,42),new Size(220,20),new Font("Segoe UI",8,FontStyle.Bold),Muted);outer.Controls.Add(line);memoryList.Location=new Point(10,70);memoryList.Size=new Size(265,570);memoryList.FlowDirection=FlowDirection.TopDown;memoryList.WrapContents=false;memoryList.AutoScroll=true;memoryList.BackColor=Color.Transparent;outer.Controls.Add(memoryList);var view=new NeonButton("⌁  VIEW ALL GAMES",Purple){Location=new Point(18,648),Size=new Size(245,42)};view.Click+=(_,_)=>ShowAllGames();outer.Controls.Add(view);var quick=CardPanel();quick.Location=new Point(0,700);quick.Size=new Size(275,210);quick.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Bottom;quick.Controls.Add(Label("QUICK ACTIONS",new Point(18,14),new Size(220,25),new Font("Segoe UI Semibold",12,FontStyle.Bold),Cyan));var clear=new NeonButton("♜  Clear Memory",Purple){Location=new Point(18,50),Size=new Size(235,36)};clear.Click+=(_,_)=>{memory.Clear();SaveMemory();RefreshMemory();};var exp=new NeonButton("⇩  Export All Reports",Cyan){Location=new Point(18,91),Size=new Size(235,36)};exp.Click+=(_,_)=>SaveReport().GetAwaiter().GetResult();var settings=new NeonButton("⚙  Settings",Purple){Location=new Point(18,132),Size=new Size(235,36)};settings.Click+=(_,_)=>MessageBox.Show("Game Route Lab is READ-ONLY. Analysis depth and memory are automatic in this build.\n\nNo router or routing changes are made.","Settings",MessageBoxButtons.OK,MessageBoxIcon.Information);outer.Controls.Add(quick);return outer;}

    Control BuildCenter(){var wrap=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,ColumnCount=1,RowCount=4,Padding=new Padding(0)};wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,215));wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,235));wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,205));wrap.RowStyles.Add(new RowStyle(SizeType.Percent,100));
        var hero=CardPanel();hero.Controls.Add(Label("AUTO ANALYSIS IN PROGRESS",new Point(180,22),new Size(700,34),new Font("Segoe UI Semibold",20,FontStyle.Bold),Purple));hero.Controls.Add(Label("Detecting game connections and analyzing routes...",new Point(180,61),new Size(700,26),new Font("Segoe UI",10.5f),Muted));progress.Location=new Point(180,99);progress.Size=new Size(700,10);progress.Style=ProgressBarStyle.Continuous;progress.Minimum=0;progress.Maximum=100;progress.Value=0;progress.ForeColor=Purple;hero.Controls.Add(progress);progressText.Text="READY";progressText.Location=new Point(895,94);progressText.Size=new Size(60,25);progressText.ForeColor=Text;hero.Controls.Add(progressText);hero.Controls.Add(new RadarControl{Location=new Point(18,28),Size=new Size(130,130),Anchor=AnchorStyles.Left|AnchorStyles.Top});var steps=new string[]{"✓\nDetect Game","✓\nFind Connections","✓\nTest Endpoints","4\nAnalyze Routes","5\nGenerate Report"};for(int i=0;i<steps.Length;i++){var l=Label(steps[i],new Point(150+i*185,145),new Size(160,55),new Font("Segoe UI",9,FontStyle.Regular),i<3?Green:i==3?Purple:Muted);l.TextAlign=ContentAlignment.TopCenter;hero.Controls.Add(l);}wrap.Controls.Add(hero,0,0);
        var summary=CardPanel();summary.Controls.Add(Label("CURRENT ANALYSIS SUMMARY",new Point(18,15),new Size(500,28),new Font("Segoe UI Semibold",13,FontStyle.Bold),Cyan));var active=InnerCard(new Point(18,55),new Size(410,155));active.Controls.Add(Label("⌁  ACTIVE GAME",new Point(18,14),new Size(260,26),new Font("Segoe UI Semibold",11,FontStyle.Bold),Cyan));gameName.Text="No game detected";gameName.Location=new Point(20,50);gameName.Size=new Size(360,30);gameName.Font=new Font("Segoe UI Semibold",15,FontStyle.Bold);active.Controls.Add(gameName);gameMeta.Text="Start an online game and click AUTO ANALYZE";gameMeta.Location=new Point(20,84);gameMeta.Size=new Size(370,60);gameMeta.ForeColor=Muted;active.Controls.Add(gameMeta);summary.Controls.Add(active);var conn=InnerCard(new Point(445,55),new Size(430,155));conn.Controls.Add(Label("⚙  CONNECTIONS DISCOVERED",new Point(18,14),new Size(360,26),new Font("Segoe UI Semibold",11,FontStyle.Bold),Cyan));conn.Controls.Add(Label("Automatically discovers public endpoints from the active game process.\nNo IP copying is required.",new Point(18,52),new Size(380,80),new Font("Segoe UI",10),Muted));summary.Controls.Add(conn);wrap.Controls.Add(summary,0,1);
        var bottom=CardPanel();var best=InnerCard(new Point(12,10),new Size(500,185));best.Controls.Add(Label("🏆  BEST ENDPOINT (CURRENT)",new Point(18,14),new Size(420,28),new Font("Segoe UI Semibold",12,FontStyle.Bold),Cyan));bestEndpoint.Text="—";bestEndpoint.Location=new Point(18,53);bestEndpoint.Size=new Size(455,32);bestEndpoint.Font=new Font("Segoe UI Semibold",17,FontStyle.Bold);bestEndpoint.ForeColor=Text;best.Controls.Add(bestEndpoint);bestMetrics.Text="LATENCY     —\nLOSS        —\nJITTER      —\nSTABILITY   —";bestMetrics.Location=new Point(18,93);bestMetrics.Size=new Size(450,75);bestMetrics.Font=new Font("Segoe UI Semibold",10);bestMetrics.ForeColor=Green;best.Controls.Add(bestMetrics);bottom.Controls.Add(best);var q=InnerCard(new Point(525,10),new Size(400,185));q.Controls.Add(Label("ROUTE QUALITY",new Point(18,14),new Size(230,28),new Font("Segoe UI Semibold",12,FontStyle.Bold),Cyan));qualityState.Text="Waiting";qualityState.Location=new Point(300,12);qualityState.Size=new Size(78,28);qualityState.ForeColor=Muted;qualityState.TextAlign=ContentAlignment.MiddleRight;q.Controls.Add(qualityState);graph.Location=new Point(18,52);graph.Size=new Size(350,90);graph.Paint+=GraphPaint;q.Controls.Add(graph);q.Controls.Add(Label("Hops: —   |   Avg Latency: —",new Point(18,151),new Size(350,25),new Font("Segoe UI",9),Muted));bottom.Controls.Add(q);wrap.Controls.Add(bottom,0,2);
        var con=CardPanel();con.Controls.Add(Label("LIVE ANALYSIS CONSOLE",new Point(18,10),new Size(350,25),new Font("Segoe UI Semibold",11,FontStyle.Bold),Cyan));console.Location=new Point(12,42);console.Size=new Size(900,120);console.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Bottom;console.BackColor=Color.FromArgb(1,4,10);console.ForeColor=Text;console.BorderStyle=BorderStyle.None;console.Font=new Font("Cascadia Mono",9);console.ReadOnly=true;console.WordWrap=false;con.Controls.Add(console);wrap.Controls.Add(con,0,3);return wrap;}

    Control BuildRight(){var wrap=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,RowCount=3,Padding=new Padding(0),ColumnCount=1};wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,230));wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,260));wrap.RowStyles.Add(new RowStyle(SizeType.Percent,100));var n=CardPanel();n.Controls.Add(Label("◌  NETWORK INFORMATION",new Point(18,16),new Size(310,28),new Font("Segoe UI Semibold",12,FontStyle.Bold),Cyan));networkInfo.Text="ISP\t—\nASN\t—\nPublic IP\t—\nLocation\t—\nConnection\t—\nDNS\t—";networkInfo.Location=new Point(20,56);networkInfo.Size=new Size(315,150);networkInfo.Font=new Font("Segoe UI",10);networkInfo.ForeColor=Text;n.Controls.Add(networkInfo);wrap.Controls.Add(n,0,0);var r=CardPanel();r.Controls.Add(Label("▣  ROUTER INFORMATION",new Point(18,16),new Size(310,28),new Font("Segoe UI Semibold",12,FontStyle.Bold),Purple));routerInfo.Text="Gateway\t—\nManufacturer\t—\nModel\t—\nFirmware\t—\nInterface\t—\nConfidence\t—";routerInfo.Location=new Point(20,56);routerInfo.Size=new Size(315,185);routerInfo.Font=new Font("Segoe UI",10);routerInfo.ForeColor=Text;r.Controls.Add(routerInfo);wrap.Controls.Add(r,0,1);var tips=CardPanel();tips.Controls.Add(Label("◉  TIPS",new Point(18,16),new Size(310,28),new Font("Segoe UI Semibold",12,FontStyle.Bold),Purple));tipText.Text="Run the analysis while the game is in an online match.\n\nMore observations = better local memory.\n\nICMP-blocked servers are not automatically treated as packet loss.\n\nThe analyzer never changes your router or Windows routes.";tipText.Location=new Point(20,58);tipText.Size=new Size(315,210);tipText.Font=new Font("Segoe UI",10);tipText.ForeColor=Muted;tips.Controls.Add(tipText);wrap.Controls.Add(tips,0,2);return wrap;}

    Panel CardPanel(){var p=new Panel{Dock=DockStyle.Fill,BackColor=Card,Margin=new Padding(0,0,0,8)};p.Paint+=CardPaint;return p;}Panel InnerCard(Point loc,Size size){var p=new Panel{Location=loc,Size=size,BackColor=Card2};p.Paint+=CardPaint;return p;}
    Label Label(string t,Point l,Size s,Font f,Color c){return new Label{Text=t,Location=l,Size=s,Font=f,ForeColor=c,BackColor=Color.Transparent};}
    void HeaderPaint(object? s,PaintEventArgs e){using var g=new LinearGradientBrush(new Rectangle(0,e.ClipRectangle.Height-4,e.ClipRectangle.Width,4),Purple,Cyan,0);e.Graphics.FillRectangle(g,0,e.ClipRectangle.Height-4,e.ClipRectangle.Width,4);}
    void CardPaint(object? s,PaintEventArgs e){var r=((Control)s!).ClientRectangle;r.Width--;r.Height--;using var p=new Pen(Line);e.Graphics.DrawRectangle(p,r);}
    void GraphPaint(object? s,PaintEventArgs e){var r=((Control)s!).ClientRectangle;e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using var grid=new Pen(Color.FromArgb(22,45,72));for(int y=10;y<r.Height;y+=20)e.Graphics.DrawLine(grid,0,y,r.Width,y);var pts=new List<Point>();var seed=current?.Samples??new List<double>();if(seed.Count<2)seed=new List<double>{56,58,54,61,57,63,59,62,60,64};for(int i=0;i<seed.Count;i++){int x=8+i*Math.Max(1,(r.Width-16)/Math.Max(1,seed.Count-1));int y=r.Height-8-(int)Math.Clamp((seed[i]-30)*1.4,8,r.Height-16);pts.Add(new Point(x,y));}using var pen=new Pen(Green,2);if(pts.Count>1)e.Graphics.DrawLines(pen,pts.ToArray());foreach(var p in pts)e.Graphics.FillEllipse(new SolidBrush(Green),p.X-2,p.Y-2,4,4);}

    async Task Safe(Func<Task> action){if(busy)return;busy=true;foreach(var a in actions)a.Enabled=false;progress.Value=5;progressText.Text="5%";try{await action();}catch(Exception ex){Write("[ERROR] "+ex.Message);qualityState.Text="Error";qualityState.ForeColor=Red;}finally{busy=false;foreach(var a in actions)a.Enabled=true;if(progress.Value<100){progress.Value=100;progressText.Text="READY";}}}
    async Task AutoAnalyze(){progress.Value=10;progressText.Text="10%";Write("\n=== AUTO ANALYSIS ===");await DetectNetwork();progress.Value=25;progressText.Text="25%";await DetectRouter();progress.Value=40;progressText.Text="40%";var games=await DiscoverGames();if(games.Count==0){gameName.Text="No high-confidence game detected";gameMeta.Text="Start an online game and run AUTO ANALYZE again.";Write("STOP: no game was detected. Normal apps are not guessed as games.");return;}var g=games.OrderByDescending(x=>x.Confidence).First();current=GetOrCreate(g);gameName.Text=current.Name;gameMeta.Text=$"PID {g.Pid}   •   Running: Yes\nPath: {g.Path}\nConfidence: {g.Confidence}%";progress.Value=55;progressText.Text="55%";var endpoints=await DiscoverEndpoints(g.Pid);Write($"Found {endpoints.Count} endpoint candidates automatically.");if(endpoints.Count==0){Write("No public game sockets visible. Enter an online match and retry.");return;}progress.Value=65;progressText.Text="65%";var results=new List<RouteResult>();foreach(var ep in endpoints.Take(8)){Write($"Testing {ep.Ip}:{ep.Port}/{ep.Protocol} ...");var ping=await Probe(ep.Ip);var trace=await TraceProbe(ep.Ip);results.Add(new RouteResult(ep,ping.Avg,trace.Hops,trace.Last,ping.Loss));}var best=results.OrderBy(r=>r.Score).First();bestEndpoint.Text=$"{best.Endpoint.Ip}:{best.Endpoint.Port}   ({best.Endpoint.Protocol})";bestMetrics.Text=$"LATENCY     {best.Ping:0} ms\nLOSS        {best.Loss:0}%\nJITTER      {best.PingJitter:0} ms\nSTABILITY   {best.Stability}";qualityState.Text=best.Score<70?"Excellent":best.Score<100?"Good":"Fair";qualityState.ForeColor=best.Score<70?Green:best.Score<100?Yellow:Red;current.LastBest=$"{best.Endpoint.Ip}:{best.Endpoint.Port}";current.BestScore=Math.Max(0,100-best.Score);current.Observations++;current.LastSeen=DateTime.Now;current.Samples.Add(best.Ping);if(current.Samples.Count>16)current.Samples.RemoveAt(0);SaveMemory();RefreshMemory();progress.Value=90;progressText.Text="90%";Write($"BEST ENDPOINT: {current.LastBest} | latency {best.Ping:0} ms | loss {best.Loss:0}% | hops {best.Hops} | score {100-best.Score:0}/100");Write("ICMP timeout is treated as blocked/unknown evidence, not automatic packet loss.");progress.Value=100;progressText.Text="100%";}

    async Task RefreshGames(){var gs=await DiscoverGames();Write($"\n=== GAME DISCOVERY: {gs.Count} high-confidence candidate(s) ===");foreach(var g in gs)Write($"{g.Name} | PID {g.Pid} | {g.Confidence}% | {g.Path}");RefreshMemory();}
    async Task DetectNetwork(){var info=await NetworkInfoAsync();networkInfo.Text=$"ISP\t{info.Isp}\nASN\t{info.Asn}\nPublic IP\t{info.PublicIp}\nLocation\t{info.Location}\nConnection\t{info.Connection}\nDNS\t{info.Dns}";Write($"NETWORK: {info.Isp} | ASN {info.Asn} | Public {info.PublicIp} | {info.Location}");}
    async Task DetectRouter(){var gw=GetGateway();var text=$"Gateway\t{gw}\nManufacturer\tUnknown\nModel\tUnknown\nFirmware\tUnknown\nInterface\tUnknown\nConfidence\tLow";try{if(!string.IsNullOrWhiteSpace(gw)){using var c=new HttpClient{Timeout=TimeSpan.FromSeconds(3)};var html=await c.GetStringAsync("http://"+gw);var low=html.ToLowerInvariant();string vendor=low.Contains("tp-link")?"TP-Link":low.Contains("huawei")?"Huawei":low.Contains("zte")?"ZTE":"Unknown";string model=low.Contains("w9960")?"TD-W9960":"Unknown";text=$"Gateway\t{gw}\nManufacturer\t{vendor}\nModel\t{model}\nFirmware\tUnknown\nInterface\tweb management\nConfidence\t{(vendor=="Unknown"?"Low":"Medium")}";}}catch{}routerInfo.Text=text;Write("ROUTER: "+text.Replace("\n"," | "));}
    async Task FindConnections(){var gs=await DiscoverGames();var g=gs.OrderByDescending(x=>x.Confidence).FirstOrDefault();if(g==null){Write("No game detected.");return;}var eps=await DiscoverEndpoints(g.Pid);Write($"\n=== CONNECTIONS FOR {g.Name} ===");foreach(var e in eps)Write($"{e.Protocol} {e.Ip}:{e.Port}");}
    async Task RouteTable(){Write("\n=== ROUTE TABLE ===");Write(await Run("route.exe","print",8000));}
    async Task Ping30(){var ip=Target();if(string.IsNullOrWhiteSpace(ip)){Write("No endpoint. Run AUTO ANALYZE or enter an IP/hostname.");return;}Write($"\n=== PING 30x {ip} ===");Write(await Run("ping.exe",$"-n 30 {ip}",45000));}
    async Task Traceroute(){var ip=Target();if(string.IsNullOrWhiteSpace(ip)){Write("No endpoint selected.");return;}Write($"\n=== TRACEROUTE {ip} ===");Write(await Run("tracert.exe",$"-d -h 30 -w 700 {ip}",40000));}
    async Task PathQuality(){var ip=Target();if(string.IsNullOrWhiteSpace(ip)){Write("No endpoint selected.");return;}Write($"\n=== PATH QUALITY {ip} ===");var p=await Probe(ip);var t=await TraceProbe(ip);qualityState.Text=p.Loss==0?"Excellent":"Review";qualityState.ForeColor=p.Loss==0?Green:Yellow;bestEndpoint.Text=ip;bestMetrics.Text=$"LATENCY     {p.Avg:0} ms\nLOSS        {p.Loss:0}%\nJITTER      {p.Jitter:0} ms\nSTABILITY   {(p.Loss==0?"Excellent":"Variable")}";Write($"Average {p.Avg:0} ms | loss {p.Loss:0}% | jitter {p.Jitter:0} ms | hops {t.Hops}");}
    async Task SaveReport(){var file=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop),$"GameRouteLab_Report_{DateTime.Now:yyyyMMdd_HHmmss}.txt");File.WriteAllText(file,console.Text+Environment.NewLine+"\n=== CURRENT ===\n"+bestEndpoint.Text+Environment.NewLine+bestMetrics.Text);Write("Report saved: "+file);await Task.CompletedTask;}

    string Target(){return string.IsNullOrWhiteSpace(endpoint.Text)?current?.LastBest?.Split(':')[0]??"":endpoint.Text.Trim();}
    string GetGateway(){try{return NetworkInterface.GetAllNetworkInterfaces().SelectMany(n=>n.GetIPProperties().GatewayAddresses).Select(g=>g.Address).FirstOrDefault(a=>a.AddressFamily==System.Net.Sockets.AddressFamily.InterNetwork)?.ToString()??"";}catch{return "";}}
    async Task<string> Run(string file,string args,int timeout){return await Task.Run(()=>{try{using var p=new Process{StartInfo=new ProcessStartInfo(file,args){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true,StandardOutputEncoding=Encoding.UTF8}};p.Start();string o=p.StandardOutput.ReadToEnd();p.WaitForExit(timeout);return o;}catch(Exception e){return e.Message;}});}
    async Task<ProbeResult> Probe(string host){var vals=new List<long>();for(int i=0;i<5;i++){try{using var p=new Ping();var r=await p.SendPingAsync(host,1000);if(r.Status==IPStatus.Success)vals.Add(r.RoundtripTime);}catch{}}if(vals.Count==0)return new ProbeResult(999,100,999);double avg=vals.Average();double jitter=vals.Count<2?0:vals.Zip(vals.Skip(1),(a,b)=>Math.Abs(a-b)).Average();return new ProbeResult(avg,(5-vals.Count)*20,jitter);}
    async Task<(int Hops,double Last)> TraceProbe(string host){var s=await Run("tracert.exe",$"-d -h 18 -w 500 {host}",22000);var lines=s.Split('\n');int hops=0;double last=0;foreach(var line in lines){if(Regex.IsMatch(line.TrimStart(),"^\\d+\\s+")){hops++;var m=Regex.Matches(line,"(\\d+)\\s*ms");if(m.Count>0)last=double.Parse(m[^1].Groups[1].Value);}}return(hops,last);}
    async Task<List<GameCandidate>> DiscoverGames(){return await Task.Run(()=>{var list=new List<GameCandidate>();foreach(var p in Process.GetProcesses()){try{if(p.HasExited||p.Id==Environment.ProcessId)continue;string n=p.ProcessName.ToLowerInvariant();if(IsBlocked(n))continue;string path="";try{path=p.MainModule?.FileName??"";}catch{}if(string.IsNullOrWhiteSpace(path))continue;int score=0;if(p.MainWindowHandle!=IntPtr.Zero)score+=20;if(!string.IsNullOrWhiteSpace(p.MainWindowTitle))score+=15;if(path.Contains("\\Games\\",StringComparison.OrdinalIgnoreCase)||path.Contains("\\Steam\\steamapps\\common\\",StringComparison.OrdinalIgnoreCase)||path.Contains("\\Epic Games\\",StringComparison.OrdinalIgnoreCase)||path.Contains("\\Riot Games\\",StringComparison.OrdinalIgnoreCase))score+=45;if(n.Contains("game")||n.Contains("crossfire")||n.Contains("valorant")||n.Contains("league")||n.Contains("fortnite")||n.Contains("pubg")||n.Contains("apex")||n.Contains("cod"))score+=25;var con=IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpConnections().Count(c=>c.ProcessId==p.Id&&c.State==TcpState.Established&&!IPAddress.IsLoopback(c.RemoteEndPoint.Address)&&!IsPrivate(c.RemoteEndPoint.Address));if(con>0)score+=20;if(score>=55)list.Add(new GameCandidate(p.Id,PrettyName(p,n),path,Math.Min(99,score)));}catch{}}return list.OrderByDescending(x=>x.Confidence).Take(20).ToList();});}
    async Task<List<Endpoint>> DiscoverEndpoints(int pid){return await Task.Run(()=>{var a=IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpConnections().Where(c=>c.ProcessId==pid&&c.State==TcpState.Established&&!IsPrivate(c.RemoteEndPoint.Address)&&!IPAddress.IsLoopback(c.RemoteEndPoint.Address)).Select(c=>new Endpoint(c.RemoteEndPoint.Address.ToString(),c.RemoteEndPoint.Port,"TCP")).ToList();return a.GroupBy(x=>$"{x.Ip}:{x.Port}").Select(g=>g.First()).ToList();});}
    static bool IsBlocked(string n){string[] x={"chatgpt","chrome","msedge","firefox","discord","steamwebhelper","steam","explorer","searchapp","searchhost","svchost","runtimebroker","onedrive","code","devenv","powershell","cmd","conhost","teams","spotify","outlook","word","excel","acrobat","widgets","phoneexperiencehost"};return x.Any(n.Contains);}
    static bool IsPrivate(IPAddress a){byte[] b=a.GetAddressBytes();return b[0]==10||b[0]==127||(b[0]==172&&b[1]>=16&&b[1]<=31)||(b[0]==192&&b[1]==168)||b[0]==169&&b[1]==254;}
    static string PrettyName(Process p,string n){try{var v=p.MainModule?.FileVersionInfo;return string.IsNullOrWhiteSpace(v?.ProductName)?p.MainWindowTitle.Length>0?p.MainWindowTitle:p.ProcessName:v.ProductName;}catch{return p.ProcessName;}}
    static async Task<NetworkSnapshot> NetworkInfoAsync(){string pub="Unknown",isp="Unknown",asn="Unknown",loc="Unknown";try{using var c=new HttpClient{Timeout=TimeSpan.FromSeconds(5)};var j=JsonDocument.Parse(await c.GetStringAsync("https://ipwho.is/"));var r=j.RootElement;if(r.TryGetProperty("ip",out var x))pub=x.GetString()??pub;if(r.TryGetProperty("city",out x)&&r.TryGetProperty("country",out var y))loc=$"{x.GetString()}, {y.GetString()}";if(r.TryGetProperty("connection",out var cn)){if(cn.TryGetProperty("isp",out x))isp=x.GetString()??isp;if(cn.TryGetProperty("asn",out x))asn="AS"+(x.GetString()??"");}}catch{}var dns=string.Join(", ",NetworkInterface.GetAllNetworkInterfaces().SelectMany(i=>i.GetIPProperties().DnsAddresses).Where(a=>a.AddressFamily==System.Net.Sockets.AddressFamily.InterNetwork).Select(a=>a.ToString()).Distinct().Take(2));return new NetworkSnapshot(isp,asn,pub,loc,"PPPoE / Ethernet",dns);}
    GameRecord GetOrCreate(GameCandidate g){var x=memory.FirstOrDefault(m=>m.Path.Equals(g.Path,StringComparison.OrdinalIgnoreCase));if(x!=null)return x;var r=new GameRecord{Key=Guid.NewGuid().ToString(),Name=g.Name,Path=g.Path,Observations=0,LastSeen=DateTime.Now,IconFile=ExtractIcon(g.Path)};memory.Add(r);return r;}
    string ExtractIcon(string path){try{if(!File.Exists(path))return "";using var icon=Icon.ExtractAssociatedIcon(path);if(icon==null)return "";string f=Path.Combine(dataDir,Guid.NewGuid()+".png");using var bmp=icon.ToBitmap();bmp.Save(f,System.Drawing.Imaging.ImageFormat.Png);return f;}catch{return "";}}
    void LoadMemory(){try{var f=Path.Combine(dataDir,"memory.json");if(File.Exists(f))memory.AddRange(JsonSerializer.Deserialize<List<GameRecord>>(File.ReadAllText(f))??new());}catch{}}
    void SaveMemory(){try{File.WriteAllText(Path.Combine(dataDir,"memory.json"),JsonSerializer.Serialize(memory,new JsonSerializerOptions{WriteIndented=true}));}catch{}}
    void RefreshMemory(){memoryList.Controls.Clear();foreach(var g in memory.OrderByDescending(x=>x.LastSeen).Take(8)){var item=new GameMemoryItem(g){Width=255,Height=78,Margin=new Padding(3)};item.Click+=(s,e)=>SelectGame(g);memoryList.Controls.Add(item);}if(memory.Count==0)memoryList.Controls.Add(Label("No games remembered yet.\n\nStart a game and click\nAUTO ANALYZE.",new Point(8,8),new Size(230,100),new Font("Segoe UI",10),Muted));footer.Text=$"Game Route Lab v5.0    •    READ-ONLY MODE    •    Windows {Environment.OSVersion.Version}    •    {DateTime.Now:HH:mm}";}
    void SelectGame(GameRecord g){current=g;gameName.Text=g.Name;gameMeta.Text=$"{g.Observations} saved analyses\nPath: {g.Path}\nBest: {g.LastBest}";bestEndpoint.Text=string.IsNullOrWhiteSpace(g.LastBest)?"—":g.LastBest;graph.Invalidate();}
    void ShowAllGames(){using var f=new Form{Text="Game Route Lab • All Games",Size=new Size(720,560),BackColor=Bg,StartPosition=FormStartPosition.CenterParent};var l=new ListBox{Dock=DockStyle.Fill,BackColor=Card,ForeColor=Text,Font=new Font("Segoe UI",11)};foreach(var g in memory)l.Items.Add($"{g.Name}    •    {g.Observations} analyses    •    Best {g.LastBest}");f.Controls.Add(l);f.ShowDialog(this);}
    void Write(string s){if(console.InvokeRequired){console.BeginInvoke(()=>Write(s));return;}console.AppendText(s+Environment.NewLine);console.SelectionStart=console.TextLength;console.ScrollToCaret();}
    record GameCandidate(int Pid,string Name,string Path,int Confidence);record Endpoint(string Ip,int Port,string Protocol);record NetworkSnapshot(string Isp,string Asn,string PublicIp,string Location,string Connection,string Dns);record ProbeResult(double Avg,double Loss,double Jitter);
    sealed class GameRecord{public string Key{get;set;}="";public string Name{get;set;}="";public string Path{get;set;}="";public int Observations{get;set;}public DateTime LastSeen{get;set;}public string LastBest{get;set;}="";public double BestScore{get;set;}public string IconFile{get;set;}="";public List<double> Samples{get;set;}=new();}
    sealed class RouteResult{public Endpoint Endpoint;public double Ping,Loss,Jitter;public int Hops;public double Last;public RouteResult(Endpoint e,double p,int h,double last,double loss){Endpoint=e;Ping=p;Hops=h;Last=last;Loss=loss;Jitter=0;}public double PingJitter=>Jitter;public double Score=>Math.Min(200,(Ping>500?100:Ping)+(Loss*2)+Hops*.5);public string Stability=>Loss==0&&Ping<80?"Excellent":Loss<20?"Good":"Variable";}

    Icon BrandIcon(){using var b=MakeLogo(64);return Icon.FromHandle(b.GetHicon());}
    Bitmap MakeLogo(int size){var b=new Bitmap(size,size);using var g=Graphics.FromImage(b);g.SmoothingMode=SmoothingMode.AntiAlias;g.Clear(Color.Transparent);using var p1=new Pen(Cyan,Math.Max(2,size/20));using var p2=new Pen(Purple,Math.Max(2,size/18));var r=new Rectangle(size/10,size/10,size*8/10,size*8/10);g.DrawPolygon(p1,new[]{new Point(size/2,size/12),new Point(size*9/10,size/3),new Point(size*3/4,size*9/10),new Point(size/4,size*9/10),new Point(size/10,size/3)});g.DrawPolygon(p2,new[]{new Point(size/2,size/5),new Point(size*4/5,size*2/5),new Point(size*7/10,size*4/5),new Point(size*3/10,size*4/5),new Point(size/5,size*2/5)});using var f=new Font("Segoe UI Black",size/4,FontStyle.Bold);var sf=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center};g.DrawString("GRL",f,Brushes.White,new RectangleF(0,size/4,size,size/2),sf);return b;}
}

sealed class NeonButton:Button{readonly Color accent;public NeonButton(string t,Color a){Text=t;accent=a;FlatStyle=FlatStyle.Flat;FlatAppearance.BorderColor=a;FlatAppearance.MouseOverBackColor=Color.FromArgb(20,25,55);BackColor=Color.FromArgb(7,14,28);ForeColor=Color.White;Font=new Font("Segoe UI Semibold",9,FontStyle.Bold);Cursor=Cursors.Hand;}
protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using var p=new Pen(Color.FromArgb(90,accent.R,accent.G,accent.B));e.Graphics.DrawRectangle(p,0,0,Width-1,Height-1);}}
sealed class IconButton:Panel{readonly Color accent;readonly string glyph,title;bool hover;public IconButton(string g,string t,Color a){glyph=g;title=t;accent=a;BackColor=Color.FromArgb(5,11,23);Cursor=Cursors.Hand;MouseEnter+=(s,e)=>{hover=true;Invalidate();};MouseLeave+=(s,e)=>{hover=false;Invalidate();};Click+=(s,e)=>{};}
protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using var bg=new SolidBrush(hover?Color.FromArgb(20,18,48):Color.FromArgb(5,11,23));e.Graphics.FillRectangle(bg,0,0,Width,Height);using var pen=new Pen(hover?accent:Color.FromArgb(35,60,95),1);e.Graphics.DrawRectangle(pen,1,1,Width-3,Height-3);using var f=new Font("Segoe UI Symbol",20);using var br=new SolidBrush(accent);e.Graphics.DrawString(glyph,f,br,new PointF(Width/2-10,6));using var tf=new Font("Segoe UI Semibold",8.5f);using var tb=new SolidBrush(Color.White);var sf=new StringFormat{Alignment=StringAlignment.Center};e.Graphics.DrawString(title,tf,tb,new RectangleF(4,38,Width-8,32),sf);}}
sealed class GameMemoryItem:Panel{readonly GameRecord g;public GameMemoryItem(GameRecord x){g=x;BackColor=Color.FromArgb(7,15,29);Cursor=Cursors.Hand;Paint+=Draw;var name=new Label{Text=g.Name,Location=new Point(70,10),Size=new Size(170,23),ForeColor=Color.White,Font=new Font("Segoe UI Semibold",10,FontStyle.Bold)};var sub=new Label{Text=$"{g.Observations} analyses\nBest: {(string.IsNullOrWhiteSpace(g.LastBest)?"—":g.LastBest)}",Location=new Point(70,34),Size=new Size(170,36),ForeColor=Color.FromArgb(40,235,110)};Controls.Add(name);Controls.Add(sub);if(File.Exists(g.IconFile)){try{var p=new PictureBox{Image=Image.FromFile(g.IconFile),Location=new Point(9,9),Size=new Size(52,52),SizeMode=PictureBoxSizeMode.Zoom};Controls.Add(p);}catch{}}}
void Draw(object? s,PaintEventArgs e){using var p=new Pen(Color.FromArgb(25,63,93));e.Graphics.DrawRectangle(p,0,0,Width-1,Height-1);}}
sealed class RadarControl:Control{public RadarControl(){DoubleBuffered=true;}protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;var c=new Point(65,65);using var p=new Pen(Color.FromArgb(120,170,70,255),2);for(int i=1;i<=3;i++)g.DrawEllipse(p,c.X-i*18,c.Y-i*18,i*36,i*36);using var pen=new Pen(Color.FromArgb(80,0,224,255),1);g.DrawLine(pen,65,8,65,122);g.DrawLine(pen,8,65,122,65);using var br=new SolidBrush(Color.FromArgb(180,181,70,255));g.FillEllipse(br,60,60,10,10);}}
