using System.Diagnostics;
using System.Drawing.Drawing2D;
using System.Net;
using System.Net.NetworkInformation;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace CrossFireRouteLab;

public sealed class ModernMainForm : Form
{
    static readonly Color Bg=Color.FromArgb(2,5,13), Card=Color.FromArgb(6,12,25), Card2=Color.FromArgb(9,17,34), Line=Color.FromArgb(27,54,88), Cyan=Color.FromArgb(0,224,255), Purple=Color.FromArgb(181,70,255), Green=Color.FromArgb(34,240,106), Yellow=Color.FromArgb(255,207,56), TextColor=Color.FromArgb(235,244,255), Muted=Color.FromArgb(135,159,190), Red=Color.FromArgb(255,74,115);
    readonly FlowLayoutPanel games=new(); readonly RichTextBox console=new(); readonly Label gameName=new(),gameMeta=new(),network=new(),router=new(),best=new(),metrics=new(),quality=new(),tips=new(),progressText=new(); readonly ProgressBar progress=new(); readonly Panel graph=new(); readonly TextBox endpoint=new(); readonly List<GameRecord> memory=new(); readonly List<IconButton> actions=new(); readonly string dataDir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"GameRouteLab"); GameRecord? current; bool busy;

    public ModernMainForm(){Text="Game Route Lab";Width=1600;Height=980;MinimumSize=new Size(1250,780);StartPosition=FormStartPosition.CenterScreen;BackColor=Bg;ForeColor=TextColor;Font=new Font("Segoe UI",9.5f);DoubleBuffered=true;Directory.CreateDirectory(dataDir);try{Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);}catch{}LoadMemory();Build();RefreshMemory();Log("GAME ROUTE LAB v5.0");Log("Smart game detection • ISP • router • endpoint • route quality • local game memory");Log("READ-ONLY MODE: no routes, DNS, PPPoE, router settings or firmware are changed.");}

    void Build(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,ColumnCount=1,RowCount=3};root.RowStyles.Add(new RowStyle(SizeType.Absolute,150));root.RowStyles.Add(new RowStyle(SizeType.Absolute,112));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.Controls.Add(Header(),0,0);root.Controls.Add(Toolbar(),0,1);var body=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,ColumnCount=3,Padding=new Padding(12,4,12,10)};body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,285));body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,355));body.Controls.Add(Left(),0,0);body.Controls.Add(Center(),1,0);body.Controls.Add(Right(),2,0);root.Controls.Add(body,0,2);Controls.Add(root);}
    Panel Header(){var p=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(1,3,9)};p.Paint+=(_,e)=>{using var b=new LinearGradientBrush(new Rectangle(0,e.ClipRectangle.Height-4,e.ClipRectangle.Width,4),Purple,Cyan,0);e.Graphics.FillRectangle(b,0,e.ClipRectangle.Height-4,e.ClipRectangle.Width,4);};p.Controls.Add(new PictureBox{Image=Logo(116),Size=new Size(120,120),Location=new Point(28,12),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.Transparent});p.Controls.Add(L("GAME ROUTE LAB",new Point(160,27),new Size(500,42),31,TextColor,true));p.Controls.Add(L("SMARTER ROUTES.  BETTER PING.",new Point(164,75),new Size(500,26),12,Cyan,true));p.Controls.Add(L("LOCAL-FIRST GAME NETWORK ANALYZER",new Point(165,103),new Size(500,22),9,Muted));return p;}
    Panel Toolbar(){var b=new FlowLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(3,7,16),Padding=new Padding(12,8,12,8),WrapContents=false,AutoScroll=true};endpoint.Width=185;endpoint.Height=42;endpoint.BackColor=Card2;endpoint.ForeColor=TextColor;endpoint.BorderStyle=BorderStyle.FixedSingle;endpoint.PlaceholderText="Optional IP / hostname";b.Controls.Add(L("ENDPOINT",Point.Empty,new Size(68,42),8,Muted));b.Controls.Add(endpoint);Add(b,"◎","AUTO ANALYZE",AutoAnalyze,Purple);Add(b,"⌁","REFRESH GAMES",RefreshGames,Cyan);Add(b,"◌","DETECT NETWORK",DetectNetwork,Cyan);Add(b,"▣","DETECT ROUTER",DetectRouter,Purple);Add(b,"⌕","FIND CONNECTIONS",FindConnections,Cyan);Add(b,"⌁","ROUTE TABLE",RouteTable,Cyan);Add(b,"◉","PING 30x",Ping30,Green);Add(b,"⇢","TRACEROUTE",Traceroute,Purple);Add(b,"▥","PATH QUALITY",PathQuality,Green);Add(b,"▤","SAVE REPORT",SaveReport,Purple);return b;}
    void Add(Control p,string glyph,string title,Func<Task> f,Color a){var b=new IconButton(glyph,title,a){Width=112,Height=78,Margin=new Padding(4,2,4,2)};b.Click+=async(_,_)=>await Safe(f);actions.Add(b);p.Controls.Add(b);}
    Panel Left(){var p=CardPanel();p.Controls.Add(L("GAME MEMORY",new Point(18,15),new Size(230,28),13,Purple,true));p.Controls.Add(L("YOUR LOCAL HISTORY",new Point(18,42),new Size(230,20),8,Muted,true));games.Location=new Point(10,70);games.Size=new Size(265,570);games.FlowDirection=FlowDirection.TopDown;games.WrapContents=false;games.AutoScroll=true;games.BackColor=Color.Transparent;p.Controls.Add(games);var view=new NeonButton("⌁  VIEW ALL GAMES",Purple){Location=new Point(18,648),Size=new Size(245,42)};view.Click+=(_,_)=>AllGames();p.Controls.Add(view);var q=CardPanel();q.Location=new Point(0,700);q.Size=new Size(275,210);q.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Bottom;q.Controls.Add(L("QUICK ACTIONS",new Point(18,14),new Size(220,25),12,Cyan,true));var c=new NeonButton("♜  Clear Memory",Purple){Location=new Point(18,50),Size=new Size(235,36)};c.Click+=(_,_)=>{memory.Clear();SaveMemory();RefreshMemory();};q.Controls.Add(c);var ex=new NeonButton("⇩  Export All Reports",Cyan){Location=new Point(18,91),Size=new Size(235,36)};ex.Click+=(_,_)=>SaveReport().GetAwaiter().GetResult();q.Controls.Add(ex);var st=new NeonButton("⚙  Settings",Purple){Location=new Point(18,132),Size=new Size(235,36)};st.Click+=(_,_)=>MessageBox.Show("READ-ONLY mode. Analysis is automatic and no router/route settings are changed.","Game Route Lab");q.Controls.Add(st);p.Controls.Add(q);return p;}
    TableLayoutPanel Center(){var t=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,RowCount=4};t.RowStyles.Add(new RowStyle(SizeType.Absolute,215));t.RowStyles.Add(new RowStyle(SizeType.Absolute,235));t.RowStyles.Add(new RowStyle(SizeType.Absolute,205));t.RowStyles.Add(new RowStyle(SizeType.Percent,100));t.Controls.Add(Hero(),0,0);t.Controls.Add(Summary(),0,1);t.Controls.Add(Bottom(),0,2);t.Controls.Add(ConsolePanel(),0,3);return t;}
    Panel Hero(){var p=CardPanel();p.Controls.Add(L("AUTO ANALYSIS IN PROGRESS",new Point(180,22),new Size(700,34),20,Purple,true));p.Controls.Add(L("Detecting game connections and analyzing routes...",new Point(180,61),new Size(700,26),10,Muted));progress.Location=new Point(180,99);progress.Size=new Size(700,10);progress.Minimum=0;progress.Maximum=100;p.Controls.Add(progress);progressText.Text="READY";progressText.Location=new Point(895,94);progressText.Size=new Size(60,25);progressText.ForeColor=TextColor;p.Controls.Add(progressText);p.Controls.Add(new RadarControl{Location=new Point(18,28),Size=new Size(130,130)});string[] s={"✓\nDetect Game","✓\nFind Connections","✓\nTest Endpoints","4\nAnalyze Routes","5\nGenerate Report"};for(int i=0;i<s.Length;i++){var x=L(s[i],new Point(150+i*185,145),new Size(160,55),9,i<3?Green:i==3?Purple:Muted);x.TextAlign=ContentAlignment.TopCenter;p.Controls.Add(x);}return p;}
    Panel Summary(){var p=CardPanel();p.Controls.Add(L("CURRENT ANALYSIS SUMMARY",new Point(18,15),new Size(500,28),13,Cyan,true));var a=Inner(new Point(18,55),new Size(410,155));a.Controls.Add(L("⌁  ACTIVE GAME",new Point(18,14),new Size(260,26),11,Cyan,true));gameName.Text="No game detected";gameName.Location=new Point(20,50);gameName.Size=new Size(360,30);gameName.Font=new Font("Segoe UI Semibold",15,FontStyle.Bold);a.Controls.Add(gameName);gameMeta.Text="Start an online game and click AUTO ANALYZE";gameMeta.Location=new Point(20,84);gameMeta.Size=new Size(370,60);gameMeta.ForeColor=Muted;a.Controls.Add(gameMeta);p.Controls.Add(a);var c=Inner(new Point(445,55),new Size(430,155));c.Controls.Add(L("⚙  CONNECTIONS DISCOVERED",new Point(18,14),new Size(360,26),11,Cyan,true));c.Controls.Add(L("Automatically discovers public endpoints from the active game process.\nNo IP copying is required.",new Point(18,52),new Size(380,80),10,Muted));p.Controls.Add(c);return p;}
    Panel Bottom(){var p=CardPanel();var b=Inner(new Point(12,10),new Size(500,185));b.Controls.Add(L("🏆  BEST ENDPOINT (CURRENT)",new Point(18,14),new Size(420,28),12,Cyan,true));best.Text="—";best.Location=new Point(18,53);best.Size=new Size(455,32);best.Font=new Font("Segoe UI Semibold",17,FontStyle.Bold);b.Controls.Add(best);metrics.Text="LATENCY     —\nLOSS        —\nJITTER      —\nSTABILITY   —";metrics.Location=new Point(18,93);metrics.Size=new Size(450,75);metrics.Font=new Font("Segoe UI Semibold",10);metrics.ForeColor=Green;b.Controls.Add(metrics);p.Controls.Add(b);var q=Inner(new Point(525,10),new Size(400,185));q.Controls.Add(L("ROUTE QUALITY",new Point(18,14),new Size(230,28),12,Cyan,true));quality.Text="Waiting";quality.Location=new Point(300,12);quality.Size=new Size(78,28);quality.TextAlign=ContentAlignment.MiddleRight;quality.ForeColor=Muted;q.Controls.Add(quality);graph.Location=new Point(18,52);graph.Size=new Size(350,90);graph.Paint+=Graph; q.Controls.Add(graph);q.Controls.Add(L("Hops: —   |   Avg Latency: —",new Point(18,151),new Size(350,25),9,Muted));p.Controls.Add(q);return p;}
    Panel ConsolePanel(){var p=CardPanel();p.Controls.Add(L("LIVE ANALYSIS CONSOLE",new Point(18,10),new Size(350,25),11,Cyan,true));console.Location=new Point(12,42);console.Size=new Size(900,120);console.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Bottom;console.BackColor=Color.FromArgb(1,4,10);console.ForeColor=TextColor;console.BorderStyle=BorderStyle.None;console.Font=new Font("Cascadia Mono",9);console.ReadOnly=true;console.WordWrap=false;p.Controls.Add(console);return p;}
    TableLayoutPanel Right(){var t=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Bg,RowCount=3};t.RowStyles.Add(new RowStyle(SizeType.Absolute,230));t.RowStyles.Add(new RowStyle(SizeType.Absolute,260));t.RowStyles.Add(new RowStyle(SizeType.Percent,100));var n=CardPanel();n.Controls.Add(L("◌  NETWORK INFORMATION",new Point(18,16),new Size(310,28),12,Cyan,true));network.Text="ISP\t—\nASN\t—\nPublic IP\t—\nLocation\t—\nConnection\t—\nDNS\t—";network.Location=new Point(20,56);network.Size=new Size(315,150);network.Font=new Font("Segoe UI",10);n.Controls.Add(network);t.Controls.Add(n,0,0);var r=CardPanel();r.Controls.Add(L("▣  ROUTER INFORMATION",new Point(18,16),new Size(310,28),12,Purple,true));router.Text="Gateway\t—\nManufacturer\t—\nModel\t—\nFirmware\t—\nInterface\t—\nConfidence\t—";router.Location=new Point(20,56);router.Size=new Size(315,185);router.Font=new Font("Segoe UI",10);r.Controls.Add(router);t.Controls.Add(r,0,1);var z=CardPanel();z.Controls.Add(L("◉  TIPS",new Point(18,16),new Size(310,28),12,Purple,true));tips.Text="Run the analysis while the game is in an online match.\n\nMore observations = better local memory.\n\nICMP-blocked servers are not automatically treated as packet loss.\n\nThe analyzer never changes your router or Windows routes.";tips.Location=new Point(20,58);tips.Size=new Size(315,210);tips.ForeColor=Muted;tips.Font=new Font("Segoe UI",10);z.Controls.Add(tips);t.Controls.Add(z,0,2);return t;}

    Panel CardPanel(){var p=new Panel{Dock=DockStyle.Fill,BackColor=Card,Margin=new Padding(0,0,0,8)};p.Paint+=BorderPaint;return p;}Panel Inner(Point x,Size s){var p=new Panel{Location=x,Size=s,BackColor=Card2};p.Paint+=BorderPaint;return p;}Label L(string text,Point loc,Size size,float font,Color color,bool bold=false)=>new(){Text=text,Location=loc,Size=size,Font=new Font("Segoe UI",font,bold?FontStyle.Bold:FontStyle.Regular),ForeColor=color,BackColor=Color.Transparent};void BorderPaint(object? s,PaintEventArgs e){var r=((Control)s!).ClientRectangle;r.Width--;r.Height--;using var p=new Pen(Line);e.Graphics.DrawRectangle(p,r);}void Graph(object? s,PaintEventArgs e){var r=((Control)s!).ClientRectangle;e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using var grid=new Pen(Color.FromArgb(22,45,72));for(int y=10;y<r.Height;y+=20)e.Graphics.DrawLine(grid,0,y,r.Width,y);var v=current?.Samples??new List<double>{56,58,54,61,57,63,59,62,60,64};var pts=v.Select((x,i)=>new Point(8+i*Math.Max(1,(r.Width-16)/Math.Max(1,v.Count-1)),r.Height-8-(int)Math.Clamp((x-30)*1.4,8,r.Height-16))).ToArray();using var p=new Pen(Green,2);if(pts.Length>1)e.Graphics.DrawLines(p,pts);foreach(var x in pts)e.Graphics.FillEllipse(Brushes.LimeGreen,x.X-2,x.Y-2,4,4);}

    async Task Safe(Func<Task> f){if(busy)return;busy=true;foreach(var a in actions)a.Enabled=false;progress.Value=5;progressText.Text="5%";try{await f();}catch(Exception e){Log("[ERROR] "+e.Message);quality.Text="Error";quality.ForeColor=Red;}finally{busy=false;foreach(var a in actions)a.Enabled=true;if(progress.Value<100){progress.Value=100;progressText.Text="READY";}}}
    async Task AutoAnalyze(){progress.Value=10;progressText.Text="10%";Log("\n=== AUTO ANALYSIS ===");await DetectNetwork();progress.Value=25;progressText.Text="25%";await DetectRouter();progress.Value=40;progressText.Text="40%";var gs=await DiscoverGames();if(gs.Count==0){gameName.Text="No high-confidence game detected";gameMeta.Text="Start an online game and run AUTO ANALYZE again.";Log("STOP: no game detected; normal applications are not guessed as games.");return;}var g=gs[0];current=GetOrCreate(g);gameName.Text=current.Name;gameMeta.Text=$"PID {g.Pid}   •   Running: Yes\nPath: {g.Path}\nConfidence: {g.Confidence}%";var eps=await Endpoints(g.Pid);Log($"Found {eps.Count} endpoint candidates automatically.");if(eps.Count==0){Log("No public game sockets visible. Enter an online match and retry.");return;}progress.Value=60;progressText.Text="60%";var rr=new List<RouteResult>();foreach(var e in eps.Take(8)){Log($"Testing {e.Ip}:{e.Port}/{e.Protocol} ...");var p=await Probe(e.Ip);var tr=await Trace(e.Ip);rr.Add(new RouteResult(e,p,tr));}var bestR=rr.OrderBy(x=>x.Score).First();best.Text=$"{bestR.E.Ip}:{bestR.E.Port}   ({bestR.E.Protocol})";metrics.Text=$"LATENCY     {bestR.P.Avg:0} ms\nLOSS        {bestR.P.Loss:0}%\nJITTER      {bestR.P.Jitter:0} ms\nSTABILITY   {bestR.Stability}";quality.Text=bestR.Score<70?"Excellent":bestR.Score<100?"Good":"Fair";quality.ForeColor=bestR.Score<70?Green:bestR.Score<100?Yellow:Red;current.LastBest=$"{bestR.E.Ip}:{bestR.E.Port}";current.BestScore=Math.Max(0,100-bestR.Score);current.Observations++;current.LastSeen=DateTime.Now;current.Samples.Add(bestR.P.Avg);if(current.Samples.Count>16)current.Samples.RemoveAt(0);SaveMemory();RefreshMemory();progress.Value=100;progressText.Text="100%";Log($"BEST: {current.LastBest} | {bestR.P.Avg:0} ms | loss {bestR.P.Loss:0}% | hops {bestR.Hops} | score {100-bestR.Score:0}/100");Log("ICMP timeout is treated as blocked/unknown evidence, not automatic packet loss.");graph.Invalidate();}
    async Task RefreshGames(){var gs=await DiscoverGames();Log($"\n=== GAME DISCOVERY: {gs.Count} candidate(s) ===");foreach(var g in gs)Log($"{g.Name} | PID {g.Pid} | {g.Confidence}% | {g.Path}");RefreshMemory();}
    async Task DetectNetwork(){var x=await NetworkInfo();network.Text=$"ISP\t{x.Isp}\nASN\t{x.Asn}\nPublic IP\t{x.PublicIp}\nLocation\t{x.Location}\nConnection\t{x.Connection}\nDNS\t{x.Dns}";Log($"NETWORK: {x.Isp} | {x.Asn} | {x.PublicIp} | {x.Location}");}
    async Task DetectRouter(){string gw=Gateway();string vendor="Unknown",model="Unknown",fw="Unknown",conf="Low";try{if(gw!=""){using var c=new HttpClient{Timeout=TimeSpan.FromSeconds(3)};string h=(await c.GetStringAsync("http://"+gw)).ToLowerInvariant();vendor=h.Contains("tp-link")?"TP-Link":h.Contains("huawei")?"Huawei":h.Contains("zte")?"ZTE":"Unknown";model=h.Contains("w9960")?"TD-W9960":"Unknown";conf=vendor=="Unknown"?"Low":"Medium";}}catch{}router.Text=$"Gateway\t{gw}\nManufacturer\t{vendor}\nModel\t{model}\nFirmware\t{fw}\nInterface\tweb management\nConfidence\t{conf}";Log($"ROUTER: {vendor} {model} | gateway {gw} | confidence {conf}");await Task.CompletedTask;}
    async Task FindConnections(){var gs=await DiscoverGames();if(gs.Count==0){Log("No game detected.");return;}var e=await Endpoints(gs[0].Pid);foreach(var x in e)Log($"{x.Protocol} {x.Ip}:{x.Port}");}
    async Task RouteTable(){Log("\n=== ROUTE TABLE ===");Log(await Run("route.exe","print",8000));}
    async Task Ping30(){string ip=Target();if(ip==""){Log("No endpoint selected.");return;}Log(await Run("ping.exe",$"-n 30 {ip}",45000));}
    async Task Traceroute(){string ip=Target();if(ip==""){Log("No endpoint selected.");return;}Log(await Run("tracert.exe",$"-d -h 30 -w 700 {ip}",40000));}
    async Task PathQuality(){string ip=Target();if(ip==""){Log("No endpoint selected.");return;}var p=await Probe(ip);var t=await Trace(ip);best.Text=ip;metrics.Text=$"LATENCY     {p.Avg:0} ms\nLOSS        {p.Loss:0}%\nJITTER      {p.Jitter:0} ms\nSTABILITY   {(p.Loss==0?"Excellent":"Variable")}";quality.Text=p.Loss==0?"Excellent":"Review";quality.ForeColor=p.Loss==0?Green:Yellow;Log($"PATH QUALITY: {p.Avg:0} ms | loss {p.Loss:0}% | jitter {p.Jitter:0} ms | hops {t.Hops}");}
    async Task SaveReport(){string f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop),$"GameRouteLab_Report_{DateTime.Now:yyyyMMdd_HHmmss}.txt");File.WriteAllText(f,console.Text+"\n=== CURRENT ===\n"+best.Text+"\n"+metrics.Text);Log("Report saved: "+f);await Task.CompletedTask;}

    string Target()=>string.IsNullOrWhiteSpace(endpoint.Text)?current?.LastBest?.Split(':')[0]??"":endpoint.Text.Trim();string Gateway(){try{return NetworkInterface.GetAllNetworkInterfaces().SelectMany(n=>n.GetIPProperties().GatewayAddresses).Select(x=>x.Address).FirstOrDefault(x=>x.AddressFamily==System.Net.Sockets.AddressFamily.InterNetwork)?.ToString()??"";}catch{return "";}}
    async Task<string> Run(string file,string args,int timeout)=>await Task.Run(()=>{try{using var p=new Process{StartInfo=new ProcessStartInfo(file,args){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true}};p.Start();string s=p.StandardOutput.ReadToEnd();p.WaitForExit(timeout);return s;}catch(Exception e){return e.Message;}});
    async Task<ProbeResult> Probe(string host){var a=new List<long>();for(int i=0;i<5;i++){try{using var p=new Ping();var r=await p.SendPingAsync(host,1000);if(r.Status==IPStatus.Success)a.Add(r.RoundtripTime);}catch{}}if(a.Count==0)return new ProbeResult(999,100,999);double avg=a.Average(),jit=a.Count<2?0:a.Zip(a.Skip(1),(x,y)=>Math.Abs(x-y)).Average();return new ProbeResult(avg,(5-a.Count)*20,jit);}
    async Task<TraceResult> Trace(string host){string s=await Run("tracert.exe",$"-d -h 18 -w 500 {host}",22000);int h=0;double last=0;foreach(var line in s.Split('\n'))if(Regex.IsMatch(line.TrimStart(),"^\\d+\\s+")){h++;var m=Regex.Matches(line,"(\\d+)\\s*ms");if(m.Count>0)last=double.Parse(m[^1].Groups[1].Value);}return new TraceResult(h,last);}
    async Task<List<GameCandidate>> DiscoverGames()=>await Task.Run(()=>{var list=new List<GameCandidate>();foreach(var p in Process.GetProcesses()){try{if(p.HasExited||p.Id==Environment.ProcessId)continue;string n=p.ProcessName.ToLowerInvariant();if(Blocked(n))continue;string path="";try{path=p.MainModule?.FileName??"";}catch{}if(path=="")continue;int s=0;if(p.MainWindowHandle!=IntPtr.Zero)s+=20;if(p.MainWindowTitle!="")s+=15;if(path.Contains("\\Games\\",StringComparison.OrdinalIgnoreCase)||path.Contains("\\steamapps\\common\\",StringComparison.OrdinalIgnoreCase)||path.Contains("\\Epic Games\\",StringComparison.OrdinalIgnoreCase)||path.Contains("\\Riot Games\\",StringComparison.OrdinalIgnoreCase))s+=45;if(n.Contains("game")||n.Contains("crossfire")||n.Contains("valorant")||n.Contains("league")||n.Contains("fortnite")||n.Contains("pubg")||n.Contains("apex")||n.Contains("cod"))s+=25;if(IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpConnections().Any(c=>c.ProcessId==p.Id&&c.State==TcpState.Established&&!Private(c.RemoteEndPoint.Address)))s+=20;if(s>=55)list.Add(new GameCandidate(p.Id,Name(p),path,Math.Min(99,s)));}catch{}}return list.OrderByDescending(x=>x.Confidence).Take(20).ToList();});
    async Task<List<Endpoint>> Endpoints(int pid)=>await Task.Run(()=>IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpConnections().Where(c=>c.ProcessId==pid&&c.State==TcpState.Established&&!Private(c.RemoteEndPoint.Address)).Select(c=>new Endpoint(c.RemoteEndPoint.Address.ToString(),c.RemoteEndPoint.Port,"TCP")).GroupBy(x=>$"{x.Ip}:{x.Port}").Select(g=>g.First()).ToList());
    static bool Blocked(string n){string[] x={"chatgpt","chrome","msedge","firefox","discord","steamwebhelper","steam","explorer","searchapp","searchhost","svchost","runtimebroker","onedrive","code","devenv","powershell","cmd","conhost","teams","spotify","outlook","word","excel","acrobat","widgets"};return x.Any(n.Contains);}static bool Private(IPAddress a){var b=a.GetAddressBytes();return b[0]==10||b[0]==127||(b[0]==172&&b[1]>=16&&b[1]<=31)||(b[0]==192&&b[1]==168)||b[0]==169&&b[1]==254;}static string Name(Process p){try{var v=p.MainModule?.FileVersionInfo;return string.IsNullOrWhiteSpace(v?.ProductName)?(p.MainWindowTitle==""?p.ProcessName:p.MainWindowTitle):v.ProductName;}catch{return p.ProcessName;}}
    static async Task<NetworkSnapshot> NetworkInfo(){string pub="Unknown",isp="Unknown",asn="Unknown",loc="Unknown";try{using var c=new HttpClient{Timeout=TimeSpan.FromSeconds(5)};using var d=JsonDocument.Parse(await c.GetStringAsync("https://ipwho.is/"));var r=d.RootElement;if(r.TryGetProperty("ip",out var x))pub=x.GetString()??pub;if(r.TryGetProperty("city",out x)&&r.TryGetProperty("country",out var y))loc=$"{x.GetString()}, {y.GetString()}";if(r.TryGetProperty("connection",out var cn)){if(cn.TryGetProperty("isp",out x))isp=x.GetString()??isp;if(cn.TryGetProperty("asn",out x))asn="AS"+(x.GetString()??"");}}catch{}string dns=string.Join(", ",NetworkInterface.GetAllNetworkInterfaces().SelectMany(i=>i.GetIPProperties().DnsAddresses).Where(x=>x.AddressFamily==System.Net.Sockets.AddressFamily.InterNetwork).Select(x=>x.ToString()).Distinct().Take(2));return new NetworkSnapshot(isp,asn,pub,loc,"PPPoE / Ethernet",dns);}
    GameRecord GetOrCreate(GameCandidate g){var x=memory.FirstOrDefault(m=>m.Path.Equals(g.Path,StringComparison.OrdinalIgnoreCase));if(x!=null)return x;var r=new GameRecord{Key=Guid.NewGuid().ToString(),Name=g.Name,Path=g.Path,IconFile=ExtractIcon(g.Path),LastSeen=DateTime.Now};memory.Add(r);return r;}string ExtractIcon(string path){try{using var i=Icon.ExtractAssociatedIcon(path);if(i==null)return "";string f=Path.Combine(dataDir,Guid.NewGuid()+".png");using var b=i.ToBitmap();b.Save(f,System.Drawing.Imaging.ImageFormat.Png);return f;}catch{return "";}}
    void LoadMemory(){try{string f=Path.Combine(dataDir,"memory.json");if(File.Exists(f))memory.AddRange(JsonSerializer.Deserialize<List<GameRecord>>(File.ReadAllText(f))??new());}catch{}}void SaveMemory(){try{File.WriteAllText(Path.Combine(dataDir,"memory.json"),JsonSerializer.Serialize(memory,new JsonSerializerOptions{WriteIndented=true}));}catch{}}
    void RefreshMemory(){games.Controls.Clear();foreach(var g in memory.OrderByDescending(x=>x.LastSeen).Take(8)){var i=new GameMemoryItem(g);i.Width=255;i.Height=78;i.Margin=new Padding(3);i.Click+=(s,e)=>Select(g);games.Controls.Add(i);}if(memory.Count==0)games.Controls.Add(L("No games remembered yet.\n\nStart a game and click\nAUTO ANALYZE.",new Point(8,8),new Size(230,100),10,Muted));}
    void Select(GameRecord g){current=g;gameName.Text=g.Name;gameMeta.Text=$"{g.Observations} saved analyses\nPath: {g.Path}\nBest: {g.LastBest}";best.Text=string.IsNullOrWhiteSpace(g.LastBest)?"—":g.LastBest;graph.Invalidate();}
    void AllGames(){using var f=new Form{Text="Game Route Lab • All Games",Size=new Size(720,560),BackColor=Bg,StartPosition=FormStartPosition.CenterParent};var l=new ListBox{Dock=DockStyle.Fill,BackColor=Card,ForeColor=TextColor,Font=new Font("Segoe UI",11)};foreach(var g in memory)l.Items.Add($"{g.Name}    •    {g.Observations} analyses    •    Best {g.LastBest}");f.Controls.Add(l);f.ShowDialog(this);}
    void Log(string s){if(console.InvokeRequired){console.BeginInvoke(()=>Log(s));return;}console.AppendText(s+Environment.NewLine);console.SelectionStart=console.TextLength;console.ScrollToCaret();}
    Bitmap Logo(int n){var b=new Bitmap(n,n);using var g=Graphics.FromImage(b);g.SmoothingMode=SmoothingMode.AntiAlias;g.Clear(Color.Transparent);using var p=new Pen(Cyan,4);using var q=new Pen(Purple,4);g.DrawPolygon(p,new[]{new Point(n/2,5),new Point(n-10,n/3),new Point(n*3/4,n-8),new Point(n/4,n-8),new Point(10,n/3)});g.DrawPolygon(q,new[]{new Point(n/2,20),new Point(n*4/5,n*2/5),new Point(n*7/10,n*4/5),new Point(n*3/10,n*4/5),new Point(n/5,n*2/5)});using var f=new Font("Segoe UI Black",n/4,FontStyle.Bold);var sf=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center};g.DrawString("GRL",f,Brushes.White,new RectangleF(0,n/4,n,n/2),sf);return b;}
    record GameCandidate(int Pid,string Name,string Path,int Confidence);record Endpoint(string Ip,int Port,string Protocol);record NetworkSnapshot(string Isp,string Asn,string PublicIp,string Location,string Connection,string Dns);record ProbeResult(double Avg,double Loss,double Jitter);record TraceResult(int Hops,double Last);record RouteResult(Endpoint E,ProbeResult P,TraceResult T){public double Score=>Math.Min(200,(P.Avg>500?100:P.Avg)+(P.Loss*2)+T.Hops*.5);public string Stability=>P.Loss==0&&P.Avg<80?"Excellent":P.Loss<20?"Good":"Variable";}
}

public sealed class GameRecord{public string Key{get;set;}="";public string Name{get;set;}="";public string Path{get;set;}="";public int Observations{get;set;}public DateTime LastSeen{get;set;}public string LastBest{get;set;}="";public double BestScore{get;set;}public string IconFile{get;set;}="";public List<double> Samples{get;set;}=new();}

sealed class NeonButton:Button{readonly Color accent;public NeonButton(string t,Color a){Text=t;accent=a;FlatStyle=FlatStyle.Flat;FlatAppearance.BorderColor=a;FlatAppearance.MouseOverBackColor=Color.FromArgb(20,25,55);BackColor=Color.FromArgb(7,14,28);ForeColor=Color.White;Font=new Font("Segoe UI Semibold",9,FontStyle.Bold);Cursor=Cursors.Hand;}protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using var p=new Pen(Color.FromArgb(100,accent.R,accent.G,accent.B));e.Graphics.DrawRectangle(p,0,0,Width-1,Height-1);}}
sealed class IconButton:Panel{readonly Color accent;readonly string glyph,title;bool hover;public IconButton(string g,string t,Color a){glyph=g;title=t;accent=a;BackColor=Color.FromArgb(5,11,23);Cursor=Cursors.Hand;MouseEnter+=(s,e)=>{hover=true;Invalidate();};MouseLeave+=(s,e)=>{hover=false;Invalidate();};}protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using var bg=new SolidBrush(hover?Color.FromArgb(20,18,48):Color.FromArgb(5,11,23));e.Graphics.FillRectangle(bg,0,0,Width,Height);using var p=new Pen(hover?accent:Color.FromArgb(35,60,95));e.Graphics.DrawRectangle(p,1,1,Width-3,Height-3);using var f=new Font("Segoe UI Symbol",20);e.Graphics.DrawString(glyph,f,new SolidBrush(accent),new PointF(Width/2-10,5));using var tf=new Font("Segoe UI Semibold",8.2f);var sf=new StringFormat{Alignment=StringAlignment.Center};e.Graphics.DrawString(title,tf,Brushes.White,new RectangleF(4,39,Width-8,32),sf);}}
sealed class GameMemoryItem:Panel{public GameMemoryItem(GameRecord g){BackColor=Color.FromArgb(7,15,29);Cursor=Cursors.Hand;Paint+=(_,e)=>{using var p=new Pen(g.BestScore>=70?Color.FromArgb(34,240,106):Color.FromArgb(25,63,93));e.Graphics.DrawRectangle(p,0,0,Width-1,Height-1);};Controls.Add(new Label{Text=g.Name,Location=new Point(70,10),Size=new Size(170,23),ForeColor=Color.White,Font=new Font("Segoe UI Semibold",10,FontStyle.Bold)});Controls.Add(new Label{Text=$"{g.Observations} analyses\nBest: {(string.IsNullOrWhiteSpace(g.LastBest)?"—":g.LastBest)}",Location=new Point(70,34),Size=new Size(170,36),ForeColor=Green});if(File.Exists(g.IconFile))try{Controls.Add(new PictureBox{Image=Image.FromFile(g.IconFile),Location=new Point(9,9),Size=new Size(52,52),SizeMode=PictureBoxSizeMode.Zoom});}catch{}}}
sealed class RadarControl:Control{public RadarControl(){DoubleBuffered=true;}protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;var c=new Point(65,65);using var p=new Pen(Color.FromArgb(120,170,70,255),2);for(int i=1;i<=3;i++)g.DrawEllipse(p,c.X-i*18,c.Y-i*18,i*36,i*36);using var q=new Pen(Color.FromArgb(80,0,224,255));g.DrawLine(q,65,8,65,122);g.DrawLine(q,8,65,122,65);g.FillEllipse(Brushes.MediumPurple,60,60,10,10);}}
